"""Change partner_groups.channel to string

Revision ID: 55078f2016b7
Revises: 0b2ea9c892af
Create Date: 2026-05-27 10:15:12.666963+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '55078f2016b7'
down_revision: Union[str, None] = '0b2ea9c892af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_groups', 'channel',
               existing_type=mysql.ENUM('DOMESTIC', 'EXPORT', 'ECOMMERCE', 'MODERN_TRADE', 'GENERAL_TRADE', 'OTHER'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partner_groups', 'channel',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('DOMESTIC', 'EXPORT', 'ECOMMERCE', 'MODERN_TRADE', 'GENERAL_TRADE', 'OTHER'),
               existing_nullable=False)
    # ### end Alembic commands ###
