"""Add unit_price to PurchaseOrder

Revision ID: e0cf0f1e4d7a
Revises: dc508fb001fe
Create Date: 2026-05-24 13:29:12.815718+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0cf0f1e4d7a'
down_revision: Union[str, None] = 'dc508fb001fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('unit_price', sa.Float(), nullable=True))
    op.alter_column('purchase_orders', 'warehouse_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'warehouse_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('purchase_orders', 'unit_price')
    # ### end Alembic commands ###
