"""initial

Revision ID: dc508fb001fe
Revises: 
Create Date: 2026-05-18 10:50:00.057768+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc508fb001fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'from_currency', 'to_currency', name='uq_exchange_rate')
    )
    op.create_index('ix_exchange_rate_period', 'exchange_rates', ['year', 'month'], unique=False)
    op.create_table('partner_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.Enum('DOMESTIC', 'EXPORT', 'ECOMMERCE', 'MODERN_TRADE', 'GENERAL_TRADE', 'OTHER', name='channeltype'), nullable=False),
    sa.Column('partner_grp_type', sa.Enum('CUSTOMER', 'SUPPLIER', name='partnergrouptype'), nullable=False),
    sa.Column('partner_grp_code', sa.String(length=50), nullable=False),
    sa.Column('partner_grp_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_groups_partner_grp_code'), 'partner_groups', ['partner_grp_code'], unique=True)
    op.create_table('product_hierarchy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('item_category_code', sa.String(length=50), nullable=False),
    sa.Column('item_category_name', sa.String(length=200), nullable=False),
    sa.Column('item_group_code', sa.String(length=50), nullable=False),
    sa.Column('item_group_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_hierarchy_brand'), 'product_hierarchy', ['brand'], unique=False)
    op.create_index(op.f('ix_product_hierarchy_business'), 'product_hierarchy', ['business'], unique=False)
    op.create_index(op.f('ix_product_hierarchy_item_category_code'), 'product_hierarchy', ['item_category_code'], unique=False)
    op.create_index(op.f('ix_product_hierarchy_item_group_code'), 'product_hierarchy', ['item_group_code'], unique=True)
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_config_key'), 'system_config', ['config_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PLANNER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_region', sa.String(length=100), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_name', sa.String(length=300), nullable=False),
    sa.Column('warehouse_attribute', sa.String(length=200), nullable=True),
    sa.Column('warehouse_status', sa.Enum('ACTIVE', 'INACTIVE', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_warehouse_code'), 'warehouses', ['warehouse_code'], unique=True)
    op.create_index(op.f('ix_warehouses_warehouse_region'), 'warehouses', ['warehouse_region'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_group_code', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_partner_code', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('item_for_name', sa.String(length=500), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.Enum('GOODS', 'FINISHED_GOODS', 'SEMI_FINISHED_GOODS', 'RAW_MATERIAL', name='itemtype'), nullable=False),
    sa.Column('item_attribute', sa.Enum('NORMAL', 'FAST_MOVING', 'SLOW_MOVING', name='itemattribute'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statustype'), nullable=False),
    sa.Column('import_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('production_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_group_code'], ['product_hierarchy.item_group_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_item_code'), 'items', ['item_code'], unique=True)
    op.create_index(op.f('ix_items_item_group_code'), 'items', ['item_group_code'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partner_grp_code', sa.String(length=50), nullable=False),
    sa.Column('partner_code', sa.String(length=50), nullable=False),
    sa.Column('partner_name', sa.String(length=300), nullable=False),
    sa.Column('partner_mst_code', sa.String(length=50), nullable=True),
    sa.Column('partner_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statustype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_grp_code'], ['partner_groups.partner_grp_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_partner_code'), 'partners', ['partner_code'], unique=True)
    op.create_index(op.f('ix_partners_partner_grp_code'), 'partners', ['partner_grp_code'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('dimension_value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_perm_user_dim', 'user_permissions', ['user_id', 'dimension'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_table('actual_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('partner_code', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_code'], ['partners.partner_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_sales_item_code'), 'actual_sales', ['item_code'], unique=False)
    op.create_index(op.f('ix_actual_sales_partner_code'), 'actual_sales', ['partner_code'], unique=False)
    op.create_index(op.f('ix_actual_sales_warehouse_code'), 'actual_sales', ['warehouse_code'], unique=False)
    op.create_index('ix_sales_item_wh_period', 'actual_sales', ['item_code', 'warehouse_code', 'year', 'month'], unique=False)
    op.create_index('ix_sales_period', 'actual_sales', ['year', 'month'], unique=False)
    op.create_table('bill_of_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finished_goods_item_code', sa.String(length=50), nullable=False),
    sa.Column('raw_material_item_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finished_goods_item_code'], ['items.item_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_material_item_code'], ['items.item_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finished_goods_item_code', 'raw_material_item_code', name='uq_bom_fg_rm')
    )
    op.create_index(op.f('ix_bill_of_materials_finished_goods_item_code'), 'bill_of_materials', ['finished_goods_item_code'], unique=False)
    op.create_index(op.f('ix_bill_of_materials_raw_material_item_code'), 'bill_of_materials', ['raw_material_item_code'], unique=False)
    op.create_table('demand_adhoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('demand_source', sa.String(length=200), nullable=True),
    sa.Column('demand_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_adhoc_item_code'), 'demand_adhoc', ['item_code'], unique=False)
    op.create_table('forecast_accuracy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('forecast_qty', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=False),
    sa.Column('fa_percent', sa.Float(), nullable=False),
    sa.Column('model_type', sa.Enum('PROPHET', 'ARIMA', 'XGBOOST', 'LSTM', 'BAYESIAN', 'ENSEMBLE', name='modeltype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accuracy_item_period', 'forecast_accuracy', ['item_code', 'year', 'month'], unique=False)
    op.create_index(op.f('ix_forecast_accuracy_item_code'), 'forecast_accuracy', ['item_code'], unique=False)
    op.create_index(op.f('ix_forecast_accuracy_warehouse_code'), 'forecast_accuracy', ['warehouse_code'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.Enum('PROPHET', 'ARIMA', 'XGBOOST', 'LSTM', 'BAYESIAN', 'ENSEMBLE', name='modeltype'), nullable=False),
    sa.Column('forecast_qty', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('adjusted_qty', sa.Float(), nullable=True),
    sa.Column('adjusted_by', sa.String(length=100), nullable=True),
    sa.Column('adjusted_at', sa.DateTime(), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_item_wh_period', 'forecast_results', ['item_code', 'warehouse_code', 'year', 'month'], unique=False)
    op.create_index('ix_forecast_model', 'forecast_results', ['model_type'], unique=False)
    op.create_index(op.f('ix_forecast_results_item_code'), 'forecast_results', ['item_code'], unique=False)
    op.create_index(op.f('ix_forecast_results_warehouse_code'), 'forecast_results', ['warehouse_code'], unique=False)
    op.create_table('inventory_onhand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_item_wh', 'inventory_onhand', ['item_code', 'warehouse_code'], unique=False)
    op.create_index(op.f('ix_inventory_onhand_item_code'), 'inventory_onhand', ['item_code'], unique=False)
    op.create_index(op.f('ix_inventory_onhand_warehouse_code'), 'inventory_onhand', ['warehouse_code'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mo_number', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('completed_qty', sa.Float(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_item_code'), 'production_orders', ['item_code'], unique=False)
    op.create_index(op.f('ix_production_orders_mo_number'), 'production_orders', ['mo_number'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('partner_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('received_qty', sa.Float(), nullable=False),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_code'], ['partners.partner_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_item_code'), 'purchase_orders', ['item_code'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('stock_in_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trans_type', sa.Enum('SUPPLIER_RECEIPT', 'PRODUCTION_RECEIPT', 'OTHER_RECEIPT', name='stockintype'), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('trans_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_in_transactions_item_code'), 'stock_in_transactions', ['item_code'], unique=False)
    op.create_table('supply_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('recommendation_type', sa.Enum('PURCHASE_ORDER', 'PRODUCTION_ORDER', 'RM_PURCHASE', name='recommendationtype'), nullable=False),
    sa.Column('forecast_qty', sa.Float(), nullable=False),
    sa.Column('safety_stock_qty', sa.Float(), nullable=False),
    sa.Column('onhand_qty', sa.Float(), nullable=False),
    sa.Column('incoming_supply_qty', sa.Float(), nullable=False),
    sa.Column('suggested_qty', sa.Float(), nullable=False),
    sa.Column('target_month', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('shortage_risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recom_item_period', 'supply_recommendations', ['item_code', 'target_year', 'target_month'], unique=False)
    op.create_index(op.f('ix_supply_recommendations_item_code'), 'supply_recommendations', ['item_code'], unique=False)
    op.create_index(op.f('ix_supply_recommendations_warehouse_code'), 'supply_recommendations', ['warehouse_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_recommendations_warehouse_code'), table_name='supply_recommendations')
    op.drop_index(op.f('ix_supply_recommendations_item_code'), table_name='supply_recommendations')
    op.drop_index('ix_recom_item_period', table_name='supply_recommendations')
    op.drop_table('supply_recommendations')
    op.drop_index(op.f('ix_stock_in_transactions_item_code'), table_name='stock_in_transactions')
    op.drop_table('stock_in_transactions')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_item_code'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_production_orders_mo_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_item_code'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_inventory_onhand_warehouse_code'), table_name='inventory_onhand')
    op.drop_index(op.f('ix_inventory_onhand_item_code'), table_name='inventory_onhand')
    op.drop_index('ix_inv_item_wh', table_name='inventory_onhand')
    op.drop_table('inventory_onhand')
    op.drop_index(op.f('ix_forecast_results_warehouse_code'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_item_code'), table_name='forecast_results')
    op.drop_index('ix_forecast_model', table_name='forecast_results')
    op.drop_index('ix_forecast_item_wh_period', table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_forecast_accuracy_warehouse_code'), table_name='forecast_accuracy')
    op.drop_index(op.f('ix_forecast_accuracy_item_code'), table_name='forecast_accuracy')
    op.drop_index('ix_accuracy_item_period', table_name='forecast_accuracy')
    op.drop_table('forecast_accuracy')
    op.drop_index(op.f('ix_demand_adhoc_item_code'), table_name='demand_adhoc')
    op.drop_table('demand_adhoc')
    op.drop_index(op.f('ix_bill_of_materials_raw_material_item_code'), table_name='bill_of_materials')
    op.drop_index(op.f('ix_bill_of_materials_finished_goods_item_code'), table_name='bill_of_materials')
    op.drop_table('bill_of_materials')
    op.drop_index('ix_sales_period', table_name='actual_sales')
    op.drop_index('ix_sales_item_wh_period', table_name='actual_sales')
    op.drop_index(op.f('ix_actual_sales_warehouse_code'), table_name='actual_sales')
    op.drop_index(op.f('ix_actual_sales_partner_code'), table_name='actual_sales')
    op.drop_index(op.f('ix_actual_sales_item_code'), table_name='actual_sales')
    op.drop_table('actual_sales')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index('ix_perm_user_dim', table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_partners_partner_grp_code'), table_name='partners')
    op.drop_index(op.f('ix_partners_partner_code'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_item_group_code'), table_name='items')
    op.drop_index(op.f('ix_items_item_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_warehouses_warehouse_region'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouse_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_config_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_product_hierarchy_item_group_code'), table_name='product_hierarchy')
    op.drop_index(op.f('ix_product_hierarchy_item_category_code'), table_name='product_hierarchy')
    op.drop_index(op.f('ix_product_hierarchy_business'), table_name='product_hierarchy')
    op.drop_index(op.f('ix_product_hierarchy_brand'), table_name='product_hierarchy')
    op.drop_table('product_hierarchy')
    op.drop_index(op.f('ix_partner_groups_partner_grp_code'), table_name='partner_groups')
    op.drop_table('partner_groups')
    op.drop_index('ix_exchange_rate_period', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
