"""Add missing columns to inventory and purchase_orders

Revision ID: 0b2ea9c892af
Revises: e0cf0f1e4d7a
Create Date: 2026-05-27 09:30:28.285343+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b2ea9c892af'
down_revision: Union[str, None] = 'e0cf0f1e4d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_onhand', sa.Column('mfg_date', sa.Date(), nullable=True))
    op.add_column('inventory_onhand', sa.Column('lot_status', sa.String(length=50), nullable=True))
    op.add_column('inventory_onhand', sa.Column('partner_code', sa.String(length=50), nullable=True))
    op.create_foreign_key('fk_inv_partner_code', 'inventory_onhand', 'partners', ['partner_code'], ['partner_code'], ondelete='RESTRICT')
    op.add_column('purchase_orders', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'currency')
    op.drop_constraint('fk_inv_partner_code', 'inventory_onhand', type_='foreignkey')
    op.drop_column('inventory_onhand', 'partner_code')
    op.drop_column('inventory_onhand', 'lot_status')
    op.drop_column('inventory_onhand', 'mfg_date')
    # ### end Alembic commands ###
